# Generated by Django 5.1.1 on 2024-11-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.service'),
        ),
    ]
