# Generated by Django 5.1.1 on 2025-03-08 08:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_not_come'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField(choices=[(7, '1 неделя'), (14, '2 недели'), (21, '3 недели'), (30, '1 месяц'), (45, '1.5 месяца'), (60, '2 месяца')], default=30)),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointment.staffmember')),
            ],
        ),
    ]
