# Generated by Django 5.1.1 on 2025-03-09 19:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_calendarsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsettings',
            name='staff_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember'),
        ),
        migrations.AlterField(
            model_name='calendarsettings',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
