# Generated by Django 5.1.1 on 2025-03-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_calendarsettings_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsettings',
            name='start_date',
        ),
    ]
