# Generated by Django 5.1.1 on 2025-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_calendarsettings_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staffmembers/'),
        ),
    ]
