# Generated by Django 5.1.1 on 2024-11-30 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_workinghours_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedappointmentrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.service'),
        ),
    ]
