# Generated by Django 5.1.1 on 2025-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_archivedappointmentrequest_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='not_come',
            field=models.BooleanField(default=False),
        ),
    ]
