# Generated by Django 5.1.1 on 2025-03-09 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_calendarsettings_staff_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsettings',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
