# Generated by Django 5.1.1 on 2024-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
